# 50 NumPy Methods

In [ ]:
# 1 (Create arry by using array function by Passing a list)

In [24]:
import numpy as np
list = [[20,25,30,50]] #1D
arry1 = np.array(list)
print(arry1)
l = [[30,40,50,60],[80,10,20,55]] #2D
arry2 = np.array(l)
print(f"\n {arry2}")
li = [[[30,40,50,60],[80,10,20,55]],[[30,40,50,60],[80,10,20,55]]] #3D
arry3 = np.array(li)
print(f"\n {arry3}")

[[20 25 30 50]]

 [[30 40 50 60]
 [80 10 20 55]]

 [[[30 40 50 60]
  [80 10 20 55]]

 [[30 40 50 60]
  [80 10 20 55]]]


In [22]:
# 2 (To Check its Dimensions use ndim)

In [25]:
print(arry1.ndim)
print(arry2.ndim)
print(arry3.ndim)

2
2
3


In [ ]:
# 3 (To Check its Data-type use dtype)

In [35]:
arry4 = np.array([1,2,4,"5"])
arry5 = np.array([1,2,3,4.0])
arry6 = np.array([1,2,3,True])
arry7 = np.array([1,2,3,True,"6",9.0])
print(arry1.dtype)
print(arry5.dtype)
print(arry4.dtype)
print(arry6.dtype)
print(arry7.dtype)
#arry7
#arry6
#arry5
#arry4

int32
float64
<U11
int32
<U11


In [ ]:
# 4 (To Check its Shape use shape) (Rows,Columns)

In [36]:
print(arry1.shape)
print(arry2.shape)
print(arry3.shape)

(1, 4)
(2, 4)
(2, 2, 4)


In [ ]:
#(create arrys without passing any list by using Functions)
#zeros #ones #eye #diag #randint #randn #rand

In [43]:
# 5 (zeros)

zeros1 = np.zeros(4) #for 1D
print(zeros1)
zeros2 = np.zeros((3,4)) #2D
print(f"\n {zeros2}")
zeros3 = np.zeros((2,5,5))
print(f"\n {zeros3}")

[0. 0. 0. 0.]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [45]:
# 6 (Ones)

ones1 = np.ones(4) #for 1D
print(ones1)
ones2 = np.ones((3,3)) #2D
print(f"\n {ones2}")
ones3 = np.ones((2,3,5))
print(f"\n {ones3}")

[1. 1. 1. 1.]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [47]:
# 7 (eye)

eyes = np.eye(5)
print(eyes)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [50]:
# 8 (diag)

diags = np.diag([6,7,8,9,10])
print(diags)

[[ 6  0  0  0  0]
 [ 0  7  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0  9  0]
 [ 0  0  0  0 10]]


In [56]:
# 9 (randint)

randints = np.random.randint(5,20,15)
print(randints)

[ 9 17 18  8 13  7 13 15 17 14 19 10  9 10 19]


In [79]:
# 10 (randn)

randns = np.random.randn(5)
print(randns)

[-0.03818415  0.67926173  1.92356141 -1.9052362  -0.95334316]


In [85]:
# 11 (rand)

rands = np.random.rand(7)
print(rands)

[0.18430659 0.28883678 0.04902933 0.18690669 0.50008958 0.69869201
 0.55020561]


In [86]:
# 12 ( To Get mean of a matrix use mean)

means = np.mean(randints)
print(means)

13.2


In [92]:
# 13 (For Reshaping of a matrix 1D to 2D,3D)

matrixx = np.random.randint(1,55,50) #1D
print(matrixx)
print(matrixx.ndim)
print(f"\n {matrixx.reshape(2,25)}") #2D
print(matrixx.reshape(2,25).ndim)
print(f"\n {matrixx.reshape(2,5,5)}") #3D
print(matrixx.reshape(2,5,5).ndim)

[31  1 51  3  8 24 30 27 22 40  5 46 42 13 29 26 10 23 29 16 12  2 45  7
 20 45 25  1 25  9  2 17  1 33 38  1 45 42 35  2 17  8 38 37 32 54 54 40
 28 18]
1

 [[31  1 51  3  8 24 30 27 22 40  5 46 42 13 29 26 10 23 29 16 12  2 45  7
  20]
 [45 25  1 25  9  2 17  1 33 38  1 45 42 35  2 17  8 38 37 32 54 54 40 28
  18]]
2

 [[[31  1 51  3  8]
  [24 30 27 22 40]
  [ 5 46 42 13 29]
  [26 10 23 29 16]
  [12  2 45  7 20]]

 [[45 25  1 25  9]
  [ 2 17  1 33 38]
  [ 1 45 42 35  2]
  [17  8 38 37 32]
  [54 54 40 28 18]]]
3


In [95]:
# 14 (Using -ve number in Reshaping)

matrixxx = np.random.randint(1,26,25)
print(matrixxx)
print(f"\n {matrixxx.reshape(5,-1)}") #Auto get Valuse for reshaping

[ 8  4 14  7 25 12 17 20 17 11 22 24 12 17 21 25  4 15 14 16  7 18 23 18
 19]

 [[ 8  4 14  7 25]
 [12 17 20 17 11]
 [22 24 12 17 21]
 [25  4 15 14 16]
 [ 7 18 23 18 19]]


In [104]:
# 15 (Seed function(use to get fixed random numbers))

np.random.seed(456)
seeed = np.random.randint(1,100,50)
print(seeed)

[28 44 90 43 29 80 61 46 38 93 40 82 12 78 70 99 79 85 35 67  5  9 86 63
 17 42 11 73 45 36 49 52 54 23 36 57 23 75 86 82  7 45 45 50 44 96 12 22
 91 90]


In [125]:
# 16 (size use to get the size of an array )

np.random.seed(13)
sizee = np.random.randint(10,30,16)
print(sizee)
sizee.size

[28 26 20 26 16 12 22 13 12 24 15 23 20 19 21 12]


16

In [133]:
# 17 (Indexing)
np.random.seed(44)
ind = np.random.randint(1,20,10)
print(ind)
print(ind[6])

[ 4 18 14  4  1  4 16 11  4  8]
16


In [134]:
# 18 (Slicing (using previous array))
print(ind[2:8])

[14  4  1  4 16 11]


In [138]:
# 19 (using 3D array for Indexing)

np.random.seed(97)
inde = np.random.randint(1,20,9).reshape(3,3)
print(inde)
print(inde[1][2])

[[ 4 10  8]
 [ 6  5 19]
 [13  5  5]]
19


In [139]:
# 21 (Using singel Bracket)

print(inde[1,2])

19


In [147]:
# 22 (Slicing)

print(inde[1:,1:])
print(f"\n {inde[1:,1:2]}")

[[ 5 19]
 [ 5  5]]

 [[5]
 [5]]


In [155]:
# 23 (View Creation)

arrr = np.array([2,4,7,9,12,45,67,89])
print(arrr)
sliced_arry = arrr[2:6]
print(sliced_arry)
sliced_arry[:] = 0
print(sliced_arry)
print(arrr)

# It make a reference with the array and change values also in their reference

[ 2  4  7  9 12 45 67 89]
[ 7  9 12 45]
[0 0 0 0]
[ 2  4  0  0  0  0 67 89]


In [156]:
# 24 (Solution of View is copy function)

arrr1 = np.array([24,11,34,56,13,3,2,7])
print(arrr1)
sliced_arry = arrr1[2:6].copy()
print(sliced_arry)
sliced_arry[:] = 0
print(sliced_arry)
print(arrr1)

[24 11 34 56 13  3  2  7]
[34 56 13  3]
[0 0 0 0]
[24 11 34 56 13  3  2  7]


In [192]:
# 25 (Empty function to create a array with its own random number according to given rows and columns)
emp = np.empty((3,4))
emp

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# 26 (To get array number use can use index number)

import numpy as np
arr1 = np.array([2,3,1,5,6,9,8,7])
arr1[[-1,1]]

array([7, 3])

In [17]:
# 26 (Conditional Selection)

arr1 = np.arange(1,10)
print(arr1)
print(arr1>5)
print(arr1[arr1>5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [18]:
arr1 = np.arange(1,10)
print(arr1)
print(arr1%2==0)
print(arr1[arr1%2==0])

[1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False]
[2 4 6 8]


In [20]:
# 27 (Operation on array)

arr = np.array([2,1,4,5]).reshape(2,2)
print(arr)
print(arr*2) #Multiply
print(arr**3) #Power
print(arr+5) #Add

[[2 1]
 [4 5]]
[[ 4  2]
 [ 8 10]]
[[  8   1]
 [ 64 125]]
[[ 7  6]
 [ 9 10]]


In [23]:
# 28 (Operation on Two array)

arr1 = np.array([5,6,7,8])
arr2 = np.array([1,2,3,4])
arr3 = np.array([9,10,11,12])
print(arr1+arr2)
print(arr2*arr3)
print(arr2**arr1+arr2)

[ 6  8 10 12]
[ 9 20 33 48]
[    2    66  2190 65540]


In [24]:
# 29 (For linear algebra multiply)

matrix1 = np.random.randint(1,15,9).reshape(3,3)
matrix2 = np.random.randint(15,30,9).reshape(3,3)

matrix1.dot(matrix2)

array([[488, 632, 632],
       [353, 419, 413],
       [335, 377, 361]])

In [35]:
# 30 (min of the array)

arr1 = np.array([4,80,90,70,1])
arr1.min()

1

In [36]:
# 31 (max)

arr1.max()

90

In [37]:
# 32 (argument min to get index of value)
arr1.argmin()

4

In [38]:
#33 (arg max)

arr1.argmax()

2

In [39]:
#34 (square root of each element)

np.sqrt(arr1)

array([2.        , 8.94427191, 9.48683298, 8.36660027, 1.        ])

In [41]:
#35 (Exponent)

np.exp(arr1)

array([5.45981500e+01, 5.54062238e+34, 1.22040329e+39, 2.51543867e+30,
       2.71828183e+00])

In [43]:
#36 (sin)

np.sin(arr1)

array([-0.7568025 , -0.99388865,  0.89399666,  0.77389068,  0.84147098])

In [44]:
#38 (cos)

np.cos(arr1)

array([-0.65364362, -0.11038724, -0.44807362,  0.6333192 ,  0.54030231])

In [47]:
#39 (linspace use to create numbers with decimal by given range)

np.linspace(1,15,5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [52]:
#40 (To Conver into Boolean)

arr = np.array([1,2,3,4,0,65],dtype="bool")
arr

array([ True,  True,  True,  True, False,  True])

In [54]:
#41 (Numpy Axis) For Axis rows=1,columns=0

np.random.seed(345)
arr1 = np.random.randint(1,11,9).reshape(3,3)
print(arr1)
print(np.sum(arr1))
np.sum(arr1,axis=1)

[[ 9  1  4]
 [10  9  5]
 [ 4  5  2]]
49


array([14, 24, 11])

In [63]:
#42 (cumulative sum)

print(np.cumsum(arr1,axis=0))
np.cumsum(arr1)

[[ 9  1  4]
 [19 10  9]
 [23 15 11]]


array([ 9, 10, 14, 24, 33, 38, 42, 47, 49], dtype=int32)

In [78]:
#43 (Shuffle use for randering an array values)

np.random.seed(123)
arr1 = np.random.randint(1,15,15)
print(arr1)
np.random.shuffle(arr1)
arr1

[14  3 13  3  7  2  4 11 12 10  7  2  1  2 10]


array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [77]:
arr1 = np.arange(15)
print(arr1)
np.random.shuffle(arr1)
arr1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 6,  5,  7,  8,  2, 11,  1, 10, 12, 13,  4,  3,  9, 14,  0])

In [81]:
#44 (Horizantal stack (place the array on right side of first))
np.random.seed(123)
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr2 = np.random.randint(20,40,9).reshape(3,3)
print(arr1)
print(arr2)
np.hstack((arr1,arr2))

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]
[[35 29 20]
 [34 20 35]
 [39 34 24]]


array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [82]:
#45 (Vertical stack (place the array in the bottom of first))

np.random.seed(123)
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)
print(matrix1)
print(matrix2)
np.vstack((matrix1,matrix2))

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]
[[35 29 20]
 [34 20 35]
 [39 34 24]]


array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [83]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [11]:
# 46 (Np.where use change value)

import numpy as np
salary = np.array([0,-1,100,2000])
np.where(salary<=0,2500,salary)

array([2500, 2500,  100, 2000])

In [5]:
np.where(salary<=0,"Not Ok","Ok")

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

In [7]:
# 47 (Ravel and flatten use to reverse arry dimension into 1D)

arry = np.random.randint(1,35,30)
print(arry.reshape(2,15))
arry.ravel()

[[32 10 33  4 20 17 10 10  1  9 14  1 31 34 19]
 [ 9 11 21 25 20  7 28 24 28  5 24 25 23 20 11]]


array([32, 10, 33,  4, 20, 17, 10, 10,  1,  9, 14,  1, 31, 34, 19,  9, 11,
       21, 25, 20,  7, 28, 24, 28,  5, 24, 25, 23, 20, 11])

In [8]:
# 48 (Now flatten)

arry.flatten()

array([32, 10, 33,  4, 20, 17, 10, 10,  1,  9, 14,  1, 31, 34, 19,  9, 11,
       21, 25, 20,  7, 28, 24, 28,  5, 24, 25, 23, 20, 11])

In [9]:
# 49 (split use to divide array)

x = [1,4,5,6,7,8,1,4]
d = np.array(x)
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([8, 1, 4])]

In [13]:
x = [[1,4,5,6,7,8,1,4],[11,14,15,16,17,19,11,14]]
d = np.array(x)
np.split(d,[4,6],axis=1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]),
 array([[ 7,  8],
        [17, 19]]),
 array([[ 1,  4],
        [11, 14]])]

In [14]:
np.split(d,[1],axis=0)

[array([[1, 4, 5, 6, 7, 8, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]

In [15]:
# 50 (Tile use to create another copy of a array)

d = np.array([1,5,7,8])
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

In [16]:
# 51 (repeat)

np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])